### ISSUE TITLE
consider_home setting or equivalent?

### ISSUE THREAD

**Issue by dave-walschot** [iMicknl/ha-sagemcom-fast#49]
Hello,

Great work and thanks alot for sharing this integration. I got my Sagemcom F5359 (KPN Netherlands) initial device tracking running in no time. 

Now the finetuning part. I would like to track how long my galaxy phone is at home each day. As you can see below the device is flicking state although it is at home.
![Image 160](https://user-images.githubusercontent.com/5054579/188489130-abb29616-9293-4963-bb91-4c85de9085e3.png)

while investigating whether I could get that solved I stumbled upon the setting "consider_home" (see https://www.home-assistant.io/integrations/device_tracker/) that documents the exact behavior I would like to have.

I just can't figure out whether the device tracker created by this integration (device_tracker.galaxy_s7) would support this setting. If so, where to set it as I cant find a file that holds the configuration of the created device trackers. If not, would there be an equivalent way of implementing the same behavior?

**Comment by iMicknl** [comment]
Sorry for the delayed reply. Afaik this feature is not part of the integration, but of Home Assistant core. You should be able to set this via HA.

**Comment by zaregg** [comment]
> Sorry for the delayed reply. Afaik this feature is not part of the integration, but of Home Assistant core. You should be able to set this via HA.

Sorry for replying to a closed issue, but I cannot figure out how one would do this. I have not found a way to edit or setup the device tracker entities in yaml so that i can add a consider_home thingy. 

I have found where it is implemented in home assistant core: [homeassistant/components/device_tracker/legacy.py](https://github.com/home-assistant/core/blob/dev/homeassistant/components/device_tracker/legacy.py)

It seems strange to me that they only have it in their legacy code.
