### ISSUE TITLE
detected integration that uses deprecated 'async_get_registry'

### ISSUE THREAD

**Issue by roelvdgun** [iMicknl/ha-sagemcom-fast#50]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |2022.10.5       |
| Integration version               | V0.2.6      |
| Sagemcom F@st model               |F5359 (KPN V12)       |
| Sagemcom F@st firmware (optional) |       |

## Describe the bug
Home assistant logger gives notification since 2022.10:

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for sagemcom_fast using this method at custom_components/sagemcom_fast/__init__.py, line 127: device_registry = await hass.helpers.device_registry.async_get_registry()

## To Reproduce

restart HA

## Expected behavior

Give a clear and concise description of what you expected to happen.
See error log, use async_get instead of async_get_registry

[bug]

**Comment by iliDaedalus** [comment]
### Since Home Assistant Version 2023.5, I noticed that this integration doesn't load anymore.

### Integration Version(s): **V0.2.6 & V0.2.7**

The error log is clear:

Logger: homeassistant.config_entries
Source: loader.py:1045
First occurred: 23:08:29 (1 occurrences)
Last logged: 23:08:29

Error setting up entry 192.168.2.254 for sagemcom_fast
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/sagemcom_fast/__init__.py", line 127, in async_setup_entry
    device_registry = await hass.helpers.device_registry.async_get_registry()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 1045, in __getattr__
    value = getattr(self._module, attr)
AttributeError: **module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'**

**Comment by iliDaedalus** [comment]
Related to:
Issue #57 
Pull request #59
